### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by FluffyDiscord** [JanSharp/quick-adjustable-inserters#3]
Was trying to put down rail signals and crash happened.

![Screenshot_1](https://github.com/user-attachments/assets/8d818ac3-6811-4210-87fd-526669229a84)

**Comment by JanSharp** [comment]
Oh right, I made a TODO for that and then forgot about it. The mod is only handling 8 directions, but there's 16 now. I'll get on fixing that.

**Comment by JanSharp** [comment]
Thanks for the report, should be fixed in `2.0.1`.

**Comment by FluffyDiscord** [comment]
Thank you!
